{
  "formatVersion": "1.1",
  "component": {
    "group": "com.archrouter.plugin",
    "module": "Plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "Plugin-1.0.0.jar",
          "url": "Plugin-1.0.0.jar",
          "size": 41844,
          "sha512": "137e39d530c7f3618b6d780ee9667a6b55398e834b6fcc3b92283a9dde6afb006d2529960df5ca53f4c09f944576a110d83963daf53b091b17eff06ab2ce9f3c",
          "sha256": "0d4f5ea4ea8664aaf2f24dc6cf1e8c7c72395c477e69a195603eaa1b20e3312a",
          "sha1": "179c193db3a45a01e8e54b36f9a226c19de7ad2f",
          "md5": "90eae54b731d08d0aaf2c2f88d3b4765"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "Plugin-1.0.0.jar",
          "url": "Plugin-1.0.0.jar",
          "size": 41844,
          "sha512": "137e39d530c7f3618b6d780ee9667a6b55398e834b6fcc3b92283a9dde6afb006d2529960df5ca53f4c09f944576a110d83963daf53b091b17eff06ab2ce9f3c",
          "sha256": "0d4f5ea4ea8664aaf2f24dc6cf1e8c7c72395c477e69a195603eaa1b20e3312a",
          "sha1": "179c193db3a45a01e8e54b36f9a226c19de7ad2f",
          "md5": "90eae54b731d08d0aaf2c2f88d3b4765"
        }
      ]
    }
  ]
}
