{
  "formatVersion": "1.1",
  "component": {
    "group": "com.archrouter.plugin.pluginRouter",
    "module": "Plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "Plugin-1.0.0.jar",
          "url": "Plugin-1.0.0.jar",
          "size": 42870,
          "sha512": "a3518dde521b7da7361b93a323655056ffa53a9ff01f28d306f9cea1a968c1cd581df33eb4693caa4226189c9a641a746d302ef845915d6b00b45d95b6c7c11a",
          "sha256": "91bb4fe7325c1af0cb524d95af8eaef3641da9a704a424dbff4fe0c6267f40c7",
          "sha1": "6673d7b1fb6bdbd417806bd8a44f9d313e528d00",
          "md5": "aa321986a72e7a20a6f55b75ce56f727"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "Plugin-1.0.0.jar",
          "url": "Plugin-1.0.0.jar",
          "size": 42870,
          "sha512": "a3518dde521b7da7361b93a323655056ffa53a9ff01f28d306f9cea1a968c1cd581df33eb4693caa4226189c9a641a746d302ef845915d6b00b45d95b6c7c11a",
          "sha256": "91bb4fe7325c1af0cb524d95af8eaef3641da9a704a424dbff4fe0c6267f40c7",
          "sha1": "6673d7b1fb6bdbd417806bd8a44f9d313e528d00",
          "md5": "aa321986a72e7a20a6f55b75ce56f727"
        }
      ]
    }
  ]
}
