{
  "formatVersion": "1.1",
  "component": {
    "group": "com.archrouter.plugin.pluginSwitch",
    "module": "Plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pluginSwitch-unspecified.jar",
          "url": "pluginSwitch-unspecified.jar",
          "size": 20498,
          "sha512": "0f58cafa31a942ecd02570df1cd52444618ba827ae423e8ff792512cb9180d0daf4e7452af6402500efa248c1300923e7c6358292fd58150d9987254e70bc4fe",
          "sha256": "247aa1c947884c6bd884b092a1c1359d329d16f3a487917da0122c2fd51c0efd",
          "sha1": "16f9018b6bb56777073c4ff59e18928168fc8636",
          "md5": "76fd85a02f629de3942a3ccecb1e9f20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "pluginSwitch-unspecified.jar",
          "url": "pluginSwitch-unspecified.jar",
          "size": 20498,
          "sha512": "0f58cafa31a942ecd02570df1cd52444618ba827ae423e8ff792512cb9180d0daf4e7452af6402500efa248c1300923e7c6358292fd58150d9987254e70bc4fe",
          "sha256": "247aa1c947884c6bd884b092a1c1359d329d16f3a487917da0122c2fd51c0efd",
          "sha1": "16f9018b6bb56777073c4ff59e18928168fc8636",
          "md5": "76fd85a02f629de3942a3ccecb1e9f20"
        }
      ]
    }
  ]
}
